[Model Monitoring] Implement default model monitoring DB values
mlrun/ce pull request #78
Opened 2023-08-14 12:05 UTC by Eyal-Danieli

Following https://github.com/v3io/helm-charts/pull/996, the model monitoring DB is generated under the existing `mlrun-db` service (as a default behaviour). 

In this PR, we update the relevant values for the default monitoring DB. It includes:
- A new value called `modelMonitoring` that at the moment includes a single field:
-- `dsn`: Model monitoring DSN database.
Please note that if and no DSN has been provided,  a new monitoring database is generated under `mlrun-db` service: `mysql+pymysql://root@mlrun-db:3306/mlrun_model_monitoring`

- Grafana `mysql` datasource credentials is now modified according to the default monitoring database. If the user has provided his own monitoring database, he will have to fill the grafana datasource credentials manually. 

A related JIRA ticket: https://jira.iguazeng.com/browse/CEML-106

2023-08-15 06:19 UTC, quaark requested changes
Looks good, minor thing

2023-08-15 06:19 UTC, quaark commented on charts/mlrun-ce/templates/config/mlrun-model-monitoring-db-config.yaml
> +{{- end }}
Maybe define a `mlrun-ce.mlrun.modelMonitoringDSN` template in the `_helpers.tpl`? See the `mlrun-ce.jupyter.mlrunUIURL` template for example

2023-08-15 06:19 UTC, quaark commented on charts/mlrun-ce/templates/config/mlrun-model-monitoring-db-config.yaml
> +{{- end -}}
also add newline please :)

2023-08-20 14:33 UTC, assaf758 approved these changes

2023-08-21 06:19 UTC, quaark approved these changes

2023-08-21 06:19 UTC, merged